name: "virunga_energies"
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+2

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  http:
  shared_preferences:
  hive:
  hive_flutter:
  socket_io_client:
  path_provider: ^2.0.0

  provider:
  permission_handler: ^11.3.1
  collection: ^1.18.0
  intl: ^0.19.0
  velocity_x: ^4.2.1
  dio:
  fl_chart: ^0.69.2
  get_storage: ^2.1.1
  rxdart: ^0.27.7
  uuid: ^4.4.0
  _fe_analyzer_shared: ^22.0.0
  modal_bottom_sheet: ^3.0.0
  pdf: ^3.10.8
  printing: ^5.12.0
  qr_flutter: ^4.1.0
  barcode: ^2.2.8
  bluetooth_print: ^4.3.0
  excel: ^4.0.2
  animated_custom_dropdown: ^3.1.1
  graphic: ^2.5.0
  date_picker_plus: ^4.1.0
  gsheets: ^0.5.0
  dropdown_button2: ^2.3.9
  font_awesome_flutter: ^10.8.0
  open_filex: ^4.7.0
  universal_html: ^2.2.4
  date_format: ^2.0.9
dev_dependencies:
  hive_generator:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.1.11
  flutter_launcher_icons: null
  simple_barcode_scanner: ^0.1.1
flutter_icons:
  android: launcher_icon
  image_path: assets/images/cero_Uzisha_Light.png
  ios: true
  remove_alpha_ios: true
  min_sdk_android: 21
flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/images/
  fonts:
    - family: GoogleSans
      fonts:
        - asset: assets/fonts/GoogleSans/GoogleSans-Bold.ttf
        - asset: assets/fonts/GoogleSans/GoogleSans-BoldItalic.ttf
        - asset: assets/fonts/GoogleSans/GoogleSans-Italic.ttf
        - asset: assets/fonts/GoogleSans/GoogleSans-Medium.ttf
        - asset: assets/fonts/GoogleSans/GoogleSans-MediumItalic.ttf
        - asset: assets/fonts/GoogleSans/GoogleSans-Regular.ttf
    - family: Karla
      fonts:
        - asset: assets/fonts/Karla/karla_bold.ttf
        - asset: assets/fonts/Karla/karla_regular.ttf
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
